name: github-actions-test

on: [push]
  branches:
    - master

jobs:
  my_test_job:
    name: my test job
    runs-on: windows-2019
    steps:
      - name: Print a greeting
        run: |
          node server
